export type FigmaRouteListItem = {
  title: string;
  path: string;
  layout?: 'dashboard';
};

export const FIGMA_ROUTE_LIST: FigmaRouteListItem[] = [
  { title: 'Home', path: '/home' },
  { title: 'Landing', path: '/' },
  { title: 'Deals Landing', path: '/deals' },
  { title: 'B2B Solutions', path: '/b2b-solutions' },
  { title: 'Terms of Service', path: '/terms' },
  { title: 'Sign Document', path: '/sign-document' },
  { title: 'Login', path: '/login' },
  { title: 'Scanner Login', path: '/scanner-login' },
  { title: 'Campaign Hub', path: '/campaigns' },
  { title: 'Campaign Detail', path: '/campaign/:id' },
  { title: 'Voucher Offers', path: '/voucher' },
  { title: 'Voucher Public', path: '/voucher/:id' },
  { title: 'Gift Card Public', path: '/gift-card/:id' },
  { title: 'Event Public', path: '/event/:id' },
  { title: 'Staff Redeem', path: '/redeem' },
  { title: 'Rental Hub', path: '/rentals' },
  { title: 'Rental Detail', path: '/rentals/:id' },
  { title: 'Shop Hub', path: '/shop' },
  { title: 'Product Detail', path: '/shop/:id' },
  { title: 'Cart', path: '/cart' },
  { title: 'Merchant Public Profile', path: '/merchant/:id' },
  { title: 'Merchant Dashboard', path: '/dashboard', layout: 'dashboard' },
  { title: 'Storefront Editor', path: '/store-builder', layout: 'dashboard' },
  { title: 'Integrations', path: '/integrations', layout: 'dashboard' },
  { title: 'User Dashboard', path: '/user-dashboard', layout: 'dashboard' },
  { title: 'Admin Dashboard', path: '/admin-dashboard', layout: 'dashboard' },
  { title: 'Email Templates', path: '/admin/email-templates', layout: 'dashboard' },
  { title: 'Analytics', path: '/analytics', layout: 'dashboard' },
  { title: 'Product Create', path: '/products/create', layout: 'dashboard' },
  { title: 'Order Create', path: '/orders/create', layout: 'dashboard' },
  { title: 'Multi Scanner', path: '/multi-scanner', layout: 'dashboard' },
  { title: 'Campaigns List', path: '/campaigns-list', layout: 'dashboard' },
  { title: 'Campaign Admin Detail', path: '/campaigns/:id/admin', layout: 'dashboard' },
  { title: 'Campaign Create', path: '/campaigns/create', layout: 'dashboard' },
  { title: 'Campaign Create Alias', path: '/create-campaign', layout: 'dashboard' },
  { title: 'News Create', path: '/news/create', layout: 'dashboard' },
  { title: 'Vouchers List', path: '/vouchers', layout: 'dashboard' },
  { title: 'Voucher Create', path: '/vouchers/create', layout: 'dashboard' },
  { title: 'Discount Codes', path: '/discounts', layout: 'dashboard' },
  { title: 'Gift Cards List', path: '/gift-cards', layout: 'dashboard' },
  { title: 'Gift Card Create', path: '/gift-cards/create', layout: 'dashboard' },
  { title: 'Events List', path: '/events', layout: 'dashboard' },
  { title: 'Event Create', path: '/events/create', layout: 'dashboard' },
  { title: 'Event Detail', path: '/events/:id', layout: 'dashboard' },
  { title: 'Event Edit', path: '/events/:id/edit', layout: 'dashboard' },
  { title: 'Promotions', path: '/promotions', layout: 'dashboard' },
  { title: 'Bonus Accounting', path: '/bonus-accounting', layout: 'dashboard' },
  { title: 'Share', path: '/share', layout: 'dashboard' },
  { title: 'User Share', path: '/user-share', layout: 'dashboard' },
  { title: 'Referrals', path: '/referrals', layout: 'dashboard' },
  { title: 'Wallet', path: '/wallet', layout: 'dashboard' },
  { title: 'Merchant Wallet', path: '/merchant-wallet', layout: 'dashboard' },
  { title: 'Email Composer', path: '/email-composer', layout: 'dashboard' },
  { title: 'Notifications', path: '/notifications', layout: 'dashboard' },
  { title: 'Billing', path: '/billing', layout: 'dashboard' },
  { title: 'QR Codes', path: '/qr-codes', layout: 'dashboard' },
  { title: 'Mobile Scanner', path: '/mobile-scanner', layout: 'dashboard' },
  { title: 'Settings', path: '/settings', layout: 'dashboard' },
  { title: 'Advanced Settings', path: '/advanced-settings', layout: 'dashboard' },
  { title: 'Merchant Onboarding', path: '/merchant-onboarding', layout: 'dashboard' },
  { title: 'Subscription Plans', path: '/subscription-plans', layout: 'dashboard' },
  { title: 'Subscription Success', path: '/subscription-success', layout: 'dashboard' },
  { title: 'Subscription Manage', path: '/subscription-manage', layout: 'dashboard' },
  { title: 'Communication Hub', path: '/extra/communication-hub', layout: 'dashboard' },
  { title: 'Finance Manager', path: '/extra/finance-manager', layout: 'dashboard' },
  { title: 'Logistics Manager', path: '/extra/logistics-manager', layout: 'dashboard' },
  { title: 'Order Manager', path: '/extra/order-manager', layout: 'dashboard' },
  { title: 'Product Manage', path: '/extra/product-manage', layout: 'dashboard' },
  { title: 'Rental Manage', path: '/extra/rental-manage', layout: 'dashboard' },
  { title: 'Warehouse', path: '/extra/warehouse', layout: 'dashboard' },
  { title: 'Component Showcase', path: '/extra/components', layout: 'dashboard' },
  { title: 'Domain Settings', path: '/extra/domain-settings', layout: 'dashboard' },
];
